language: go
sudo: false

env:
  global:
    - CURRENT_GO_VERSION="1.7"

go:
  - 1.6.x
  - 1.7.x
  - master

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/philwinder/gocoverage
  - go get github.com/kisielk/errcheck

script:
  - go test -race -v . ./cmd/...
  - go vet . ./cmd/...
  - errcheck . ./cmd/...
  - diff <(gofmt -d .) <(echo -n "")
  - if [[ $TRAVIS_GO_VERSION =~ $CURRENT_GO_VERSION ]]; then
      gocoverage && goveralls -coverprofile=profile.cov -service=travis-ci || true;
    fi
